name: ci

on:
  push:
    branches-ignore:
      - backup3
      - gh-pages
  pull_request:
    branches-ignore:
      - backup3
      - gh-pages

jobs:
  windows_mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
      - name: Build primecount
        run: |
            cmake . -G "Unix Makefiles" -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
            grep "^OpenMP:INTERNAL=1$" CMakeCache.txt
            grep "^int128.*:INTERNAL=1$" CMakeCache.txt
            grep "^cpu_supports_popcnt:INTERNAL=1$" CMakeCache.txt
            make -j2 VERBOSE=1
      - uses: actions/upload-artifact@v3	
        with:	
          name: primecount
          path: primecount*
      # The current MinGW/GCC-12.1 version miscompiles primesieve/primecount,
      # many tests fail with an exception thrown.
      #- name: CTest (unit tests)
      #  run: ctest -j2
      #- name: primecount --test option
      #  run: ./primecount --test
